version: "3"

services:
    prometheus:
        image: prom/prometheus:v2.35.0
        container_name: prometheus
        restart: unless-stopped
        volumes:
            - ./data/prometheus/config:/etc/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yaml'
        ports:
            - '9090:9090'
        networks:
            - promnet

    grafana:
        image: grafana/grafana:6.7.2
        container_name: grafana
        ports:
            - '3000:3000'
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false
        restart: unless-stopped
        networks:
            - promnet
        labels:
            org.label-schema.group: "monitoring"

networks:
    promnet:
        driver: bridge


